properties:
  - type: text
    name: WORKSPACE_ID
    value: ${WORKSPACE_ID}
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: text
    name: ibmcloud-api
    value: ${IBM_CLOUD_API}
  - type: secure
    name: toolchain-apikey
    value: ${API_KEY}
  - name: workspace-id
    value: ${WORKSPACE_ID}
    type: text
  - name: terraform-request
    value: ${TERRAFORM_REQUEST}
    type: secure
  - name: console-solutions-api
    value: ${CONSOLE_SOLUTIONS_API}
    type: text
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
triggers:
  - type: manual
    name: template-download-manual-trigger
    eventListener: template-download-trigger-listener
inputs:
  - type: git
    path: .tekton
    branch: ${TEMPLATE_BRANCH}
    service: ${schematics-pipeline}
  - type: git
    path: git
    branch: ${CATALOG_BRANCH}
    service: ${tekton-catalog}
  - type: git
    path: toolchain
    branch: ${CATALOG_BRANCH}
    service: ${tekton-catalog}
