---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: template-download-pipeline
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: branch
      description: the branch for the git repo
      default: "main"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: apikey
      description: The IBM Cloud API key
    - name: workspace-id
      description: Schematics Workspace ID
      default: "0"
    - name: terraform-request
      description: The Terraform request body
    - name: console-solutions-api
      description: The endpoint URL for the Console Solutions API
      default: "https://cloud.ibm.com/solutions-api/v1"
    - name: pipeline-debug
  workspaces:
    - name: artifacts
  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          # if a params.repository is given, it takes precedence
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="terraform-template") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: git-clone
      runAfter: extract-repository-url
      taskRef:
        name: git-clone-repo
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "toolchain-apikey"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: directory-name
          value: schematics-workspace-$(params.workspace-id)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: artifacts
    - name: schematics-workspace-setup
      runAfter: git-clone
      taskRef:
        name: schematics-workspace-setup
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: devops-apikey
          value: $(params.apikey)
        - name: repository
          value: $(tasks.git-clone.results.git-repository)
        - name: branch
          value: $(tasks.git-clone.results.git-branch)
        - name: revision
          value: $(tasks.git-clone.results.git-commit)
        - name: workspace-id
          value: $(params.workspace-id)
        - name: terraform-request
          value: $(params.terraform-request)
        - name: console-solutions-api
          value: $(params.console-solutions-api)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: artifacts
          workspace: artifacts
