---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-download-template
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
      default: "main"
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: apikey
      description: The IBM Cloud API key
    - name: workspace-id
      description: Schematics Workspace ID
    - name: terraform-request
      description: The Terraform request body
    - name: console-solutions-api
      description: The endpoint URL for the Console Solutions API
      default: "https://cloud.ibm.com/solutions-api/v1"
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: template-download-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: apikey
            value: $(params.apikey)
          - name: workspace-id
            value: $(params.workspace-id)
          - name: terraform-request
            value: $(params.terraform-request)
          - name: console-solutions-api
            value: $(params.console-solutions-api)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
